shell.run("pastebin get XFgHwpHA startup")
sleep(1)
shell.run("wget https://raw.githubusercontent.com/simadude/buccshot/refs/heads/main/buccshot.lua buccshot.lua")
sleep(1)
shell.run("wget run https://raw.githubusercontent.com/knijn/musicify/main/install.lua")
sleep(1)
shell.run("set musicify.repo https://raw.githubusercontent.com/Catboy-Riku/NyatOS/main/index.json")
sleep(1)
shell.run("reboot")
