shell.run("pastebin get jewpSesL startup")
sleep(1)
shell.run("wget run https://raw.githubusercontent.com/knijn/musicify/main/install.lua")
sleep(1)
shell.run("set musicify.repo https://raw.githubusercontent.com/Catboy-Riku/musicify-songs/main/index.json")
sleep(1)
shell.run("reboot")
